with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName}}.go"
outpkg: mocks
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/bnema/uinputd-go/internal/uinput:
    interfaces:
      DeviceInterface:
  github.com/bnema/uinputd-go/internal/layouts:
    interfaces:
      RegistryInterface:
      Layout:
